In [2]:
import numpy as  np
from sklearn.linear_model import LinearRegression

In [3]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])
print(x)
print(y)

[[ 5]
 [15]
 [25]
 [35]
 [45]
 [55]]
[ 5 20 14 32 22 38]


In [4]:
model = LinearRegression().fit(x, y)

r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)



coefficient of determination: 0.7158756137479542


vytvori instanci LinearRegression 

- fit_intercept is bool - true - vypocita interpret b0 - false - poazuje za 0 - dafauld = 0

- normalize - True  -   normalizuje vztupni promnenne
            - False -   nenormalizuje = DEFAULD

- copy_x    - True  -   jestli kopírovat = DEFALUD
            - False -   přepsat vztupní poměnné 

- n_jobs    - Int ot None - počet praí vykonanných v paralerních výpočtech DEFAULD = None - co znamena 1 práci

In [5]:
print('intercept:', model.intercept_)
print('slope:', model.coef_)


intercept: 5.633333333333329
slope: [0.54]


In [6]:
new_model = LinearRegression().fit(x,y.reshape((-1,1)))
print('intercept:', new_model.intercept_)
print('slope:', new_model.coef_)

intercept: [5.63333333]
slope: [[0.54]]


Podobný výsledek jako u prvniho přípdau, jenom že je intercapt je 1D pole a coef je 2D pole.


In [7]:
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

y_pred = model.intercept_ + model.coef_ * x
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]
predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [8]:
x_new = np.arange(5).reshape((-1, 1))
x_new

y_new = model.predict(x_new)
y_new

array([5.63333333, 6.17333333, 6.71333333, 7.25333333, 7.79333333])

# Multiple Linear Regrassion

In [9]:
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

In [10]:
model = LinearRegression().fit(x, y)
r_sq = model.score(x,y)


In [11]:
print('coefficient of determination:', r_sq)
print('intercept:', model.intercept_)
print('slope:', model.coef_)

coefficient of determination: 0.8615939258756776
intercept: 5.52257927519819
slope: [0.44706965 0.25502548]


- intercept_ =  drzi b 
- coef_ = pole 𝑏₁ a 𝑏₂

### Predpovezeni vysledku


In [12]:
y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


predict === y_pred = model.intercept_ + np.sum(model.coef_ * x, axis=1)


In [13]:
y_pred = model.intercept_ + np.sum(model.coef_ * x, axis=1)
print(f"predicted response:\n{y_pred}")

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [14]:
x_new = np.arange(10).reshape((-1, 2))
print(x_new)

y_new = model.predict(x_new)
print(y_new)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[ 5.77760476  7.18179502  8.58598528  9.99017554 11.3943658 ]


# Polynomial Regression
- Podobná lineární - musíme transformovat pole vstupu, aby obsahovali nelineární členy jako 𝑥² 


In [15]:
from sklearn.preprocessing import PolynomialFeatures

In [16]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([15,11,2,8,25,32])

Pottřebujeme 2D pole proto.reshape

## Transform data 

You can provide several optional parameters to PolynomialFeatures:

- degree is an integer (2 by default) that represents the degree of the polynomial regression function.
- interaction_only is a Boolean (False by default) that decides whether to include only interaction features (True) or all features (False).
- include_bias is a Boolean (True by default) that decides whether to include the bias, or intercept, column of 1 values (True) or not (False).

In [17]:
transformer = PolynomialFeatures(degree=2, include_bias=False)
transformer.fit(x)
x_ = transformer.transform(x)
print(x_)
print(x_.shape)

[[   5.   25.]
 [  15.  225.]
 [  25.  625.]
 [  35. 1225.]
 [  45. 2025.]
 [  55. 3025.]]
(6, 2)


In [18]:
model = LinearRegression().fit(x_, y)
r_sq = model.score(x_, y)
print('coefficient of determination:', r_sq)

print('intercept:', model.intercept_)

print('coefficients:', model.coef_)


coefficient of determination: 0.8908516262498564
intercept: 21.37232142857144
coefficients: [-1.32357143  0.02839286]


- .score vrátí R^2 
- .intercept - reprezentujeb0
- .coef_ - reprezentuje b1 a b2
 

In [ ]:
x_ = PolynomialFeatures(degree=2, include_bias=True).fit_transform(x)
x_


array([[1.000e+00, 5.000e+00, 2.500e+01],
       [1.000e+00, 1.500e+01, 2.250e+02],
       [1.000e+00, 2.500e+01, 6.250e+02],
       [1.000e+00, 3.500e+01, 1.225e+03],
       [1.000e+00, 4.500e+01, 2.025e+03],
       [1.000e+00, 5.500e+01, 3.025e+03]])

In [21]:
model = LinearRegression(fit_intercept=False).fit(x_, y)
r_sq = model.score(x_, y)
print('coefficient of determination:', r_sq)
print('intercept:', model.intercept_)
print('coefficients:', model.coef_)

coefficient of determination: 0.8908516262498564
intercept: 0.0
coefficients: [21.37232143 -1.32357143  0.02839286]


In [22]:
y_pred = model.predict(x_)
print(f"predicted response : {y_pred}")


predicted response : [15.46428571  7.90714286  6.02857143  9.82857143 19.30714286 34.46428571]


# Advanced Linear Regression With statsmodels
- muzeme pouzit taky package - statsmodel - poziva se pro vice detailni vysledky
- procedura je podobna jako u scikit-learn 


In [ ]:
import statsmodels.api as sm

In [24]:
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)

Potrebujeme pridat radek s 1 do vstupu - statsmodel potrebuje pro vypocet b0 - nepouziva ho automaticky

In [25]:
x = sm.add_constant(x)
print(x)

[[ 1.  0.  1.]
 [ 1.  5.  1.]
 [ 1. 15.  2.]
 [ 1. 25.  5.]
 [ 1. 35. 11.]
 [ 1. 45. 15.]
 [ 1. 55. 34.]
 [ 1. 60. 35.]]


In [26]:
model = sm.OLS(y, x)
results = model.fit()

In [27]:
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.862
Model:                            OLS   Adj. R-squared:                  0.806
Method:                 Least Squares   F-statistic:                     15.56
Date:                Tue, 06 May 2025   Prob (F-statistic):            0.00713
Time:                        10:37:33   Log-Likelihood:                -24.316
No. Observations:                   8   AIC:                             54.63
Df Residuals:                       5   BIC:                             54.87
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          5.5226      4.431      1.246      0.2

/media/rih0075/HDDv02/Ubuntu/6.sem/PDS/F1-Prediction-PDS-Parallel/env/lib/python3.12/site-packages/scipy/stats/_axis_nan_policy.py:430: UserWarning: `kurtosistest` p-value may be inaccurate with fewer than 20 observations; only n=8 observations were given.
  return hypotest_fun_in(*args, **kwds)


In [28]:
print(f"predicted response:\n{results.fittedvalues}")

predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]


In [29]:
x_new =  sm.add_constant(np.arange(10).reshape((-1, 2)))
print(x_new)


[[1. 0. 1.]
 [1. 2. 3.]
 [1. 4. 5.]
 [1. 6. 7.]
 [1. 8. 9.]]


In [30]:
y_new = results.predict(x_new)
print(y_new)

[ 5.77760476  7.18179502  8.58598528  9.99017554 11.3943658 ]
